name: Bug Report (Server)
description: Create a report to help us fix a bug in the server.
labels: bug, server

body:
  - type: textarea
    id: summary
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      value: |
        1. Go to '…'
        2. Click on '…'
        3. Scroll down to '…'
        4. Error: …
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: Logs
      description: Relevant log output from the server.
      render: text

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: input
    id: java-version
    attributes:
      label: Java Version
      description: The version of the Java compiler and runtime.
      placeholder: e.g. "OpenJDK 21, Oracle Java 17"
    validations:
      required: true

  - type: input
    id: server-version
    attributes:
      label: Server Version
      description: The version of the server.
      placeholder: e.g. "f3286e4181f360f40f52e05c845670753f0810e6"
    validations:
      required: true

  - type: input
    id: wl-version
    attributes:
      label: Widelands Version
      description: The version of the Widelands client.
      placeholder: e.g. "v1.2", "73f9eb5c0b26599b72609f3e27de569f49049269"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.

