name: Bug Report (Add-On)
description: Report a bug in an add-on.
labels: bug

body:
  - type: markdown
    attributes:
      value: |
        Please note that add-ons are not maintained by the Widelands Development Team.
        The responsibility for fixing bugs in an add-on lies with the add-on's author.
        Issues here will be forwarded to the author, but there is no guarantee that the author will address the issue.

  - type: input
    id: addon-name
    attributes:
      label: Add-On Name
      description: The add-on this bug report is about.
      placeholder: e.g. "europeans_main.wad", "Frisians Economy Ultra"
    validations:
      required: true

  - type: input
    id: addon-version
    attributes:
      label: Add-On Version
      description: The version of the add-on.
      placeholder: e.g. "v1.9.4", "v2.2.2"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      value: |
        1. Go to '…'
        2. Click on '…'
        3. Scroll down to '…'
        4. Error: …
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: textarea
    id: replays
    attributes:
      label: Replays
      description: If applicable, include a replay demonstrating the problem or leading to a crash.

  - type: textarea
    id: savegames
    attributes:
      label: Savegames
      description: If applicable, include a savegame demonstrating the problem or helping to reproduce it.

  - type: input
    id: os-version
    attributes:
      label: Operating System
      description: The version of the operating system.
      placeholder: e.g. "Ubuntu 24.04", "Windows 11 64-bit"
    validations:
      required: true

  - type: input
    id: wl-version
    attributes:
      label: Widelands Version
      description: The version of Widelands.
      placeholder: e.g. "v1.2", "73f9eb5c0b26599b72609f3e27de569f49049269"
    validations:
      required: true

  - type: textarea
    id: addons-versions
    attributes:
      label: Enabled Add-Ons
      description: All enabled add-ons
      placeholder: e.g. "frisians-economy-ultra.wad", "Frisians Economy Ultra"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.

