return {
   summer_flowering_meadow1 = {"__skip_if_exists"},
   summer_flowering_meadow2 = {"__skip_if_exists"},
   summer_flowering_meadow3 = {"__skip_if_exists"},
   summer_flowering_meadow4 = {"__skip_if_exists"},
   summer_clearing1 = {"__skip_if_exists"},
   summer_clearing2 = {"__skip_if_exists"},
   summer_clearing3 = {"__skip_if_exists"},
   summer_forested_dolomites1 = {"__skip_if_exists"},
   summer_forested_dolomites2 = {"__skip_if_exists"},
   summer_forested_dolomites3 = {"__skip_if_exists"},
   summer_dolomites1 = {"__skip_if_exists"},
   summer_dolomites2 = {"__skip_if_exists"},
   summer_dolomites_meadow = {"__skip_if_exists"},
   summer_wet_beach = {"__skip_if_exists"},
   summer_green_water1 = {"__skip_if_exists"},
   summer_green_water2 = {"__skip_if_exists"},
   summer_green_water3 = {"__skip_if_exists"},
   summer_muddy_water = {"__skip_if_exists"},
}
