return {
   tropics_soil1 = {"__skip_if_exists"},
   tropics_soil2 = {"__skip_if_exists"},
   tropics_soil3 = {"__skip_if_exists"},
   tropics_soil4 = {"__skip_if_exists"},
   tropics_rocky_soil1 = {"__skip_if_exists"},
   tropics_rocky_soil2 = {"__skip_if_exists"},
   tropics_forest_mountain1 = {"__skip_if_exists"},
   tropics_forest_mountain2 = {"__skip_if_exists"},
   tropics_forest_mountain3 = {"__skip_if_exists"},
   tropics_mountain1 = {"__skip_if_exists"},
   tropics_mountain2 = {"__skip_if_exists"},
   tropics_mountain3 = {"__skip_if_exists"},
   tropics_beach = {"__skip_if_exists"},
   tropics_fen1 = {"__skip_if_exists"},
   tropics_fen2 = {"__skip_if_exists"},
   tropics_swamp = {"__skip_if_exists"},
   tropics_water1 = {"__skip_if_exists"},
   tropics_water2 = {"__skip_if_exists"},
}
