local D = wl.Descriptions()
D:modify_unit("terrain", "wasteland_water", "textures", {fps = 10, textures = path.list_files(path.dirname(__file__) .. "blackland_water/water_??.png" )})
D:modify_unit("terrain", "winter_water",    "textures", {fps =  8, textures = path.list_files(path.dirname(__file__) .. "winterland_water/water_??.png")})
D:modify_unit("terrain", "summer_water",    "textures", {fps = 10, textures = path.list_files(path.dirname(__file__) .. "greenland_water/wasser_??.png")})
D:modify_unit("terrain", "desert_water",    "textures", {fps =  5, textures = path.list_files(path.dirname(__file__) .. "desert/wasser_??.png"         )})
D:modify_unit("terrain", "desert_beach",    "textures", {          textures = path.list_files(path.dirname(__file__) .. "desert/beach_??.png"          )})
D:modify_unit("terrain", "drysoil",         "textures", {          textures = path.list_files(path.dirname(__file__) .. "desert/drysoil_??.png"        )})
D:modify_unit("terrain", "desert1",         "textures", {          textures = path.list_files(path.dirname(__file__) .. "desert/desert1_??.png"        )})
D:modify_unit("terrain", "desert2",         "textures", {          textures = path.list_files(path.dirname(__file__) .. "desert/desert2_??.png"        )})
D:modify_unit("terrain", "desert3",         "textures", {          textures = path.list_files(path.dirname(__file__) .. "desert/desert3_??.png"        )})
D:modify_unit("terrain", "desert4",         "textures", {          textures = path.list_files(path.dirname(__file__) .. "desert/desert4_??.png"        )})
