return {
   foreignplanet_rocks1 = {"__skip_if_exists"},
   foreignplanet_rocks2 = {"__skip_if_exists"},
   foreignplanet_rocks3 = {"__skip_if_exists"},
   foreignplanet_rocks4 = {"__skip_if_exists"},
   foreignplanet_rocks5 = {"__skip_if_exists"},
   foreignplanet_rocks6 = {"__skip_if_exists"},
   foreignplanet_mountain1 = {"__skip_if_exists"},
   foreignplanet_mountain2 = {"__skip_if_exists"},
   foreignplanet_mountain3 = {"__skip_if_exists"},
   foreignplanet_beach = {"__skip_if_exists"},
   foreignplanet_dust1 = {"__skip_if_exists"},
   foreignplanet_dust2 = {"__skip_if_exists"},
   foreignplanet_water1 = {"__skip_if_exists"},
   foreignplanet_water2 = {"__skip_if_exists"},
}
