----------------------------------------------------------------------------------------------
--                         Empire militarysites
----------------------------------------------------------------------------------------------

if N then

D:modify_unit("militarysite", "empire_barrier", "conquers", 9)
D:modify_unit("militarysite", "empire_barrier", "max_soldiers", 3)
D:modify_unit("militarysite", "empire_barrier", "heal_per_second", 0)

D:modify_unit("building", "empire_blockhouse", "buildcost", "remove", "planks")
D:modify_unit("building", "empire_blockhouse", "buildcost", "set", "log", 3)
D:modify_unit("building", "empire_blockhouse", "return_on_dismantle", "remove", "planks")
D:modify_unit("building", "empire_blockhouse", "return_on_dismantle", "set", "log", 1)
D:modify_unit("building", "empire_blockhouse", "vision_range", 14)
D:modify_unit("militarysite", "empire_blockhouse", "heal_per_second", 0)

D:modify_unit("building", "empire_fortress", "enhancement_cost", "remove", "marble_column")
D:modify_unit("building", "empire_fortress", "enhancement_cost", "remove", "marble")
D:modify_unit("building", "empire_fortress", "enhancement_cost", "remove", "planks")
D:modify_unit("building", "empire_fortress", "enhancement_cost", "remove", "granite")
D:modify_unit("building", "empire_fortress", "enhancement_cost", "set", "log", 2)
D:modify_unit("building", "empire_fortress", "enhancement_return_on_dismantle", "remove", "marble_column")
D:modify_unit("building", "empire_fortress", "enhancement_return_on_dismantle", "remove", "marble")
D:modify_unit("building", "empire_fortress", "enhancement_return_on_dismantle", "remove", "planks")
D:modify_unit("building", "empire_fortress", "enhancement_return_on_dismantle", "remove", "granite")
D:modify_unit("building", "empire_fortress", "enhancement_return_on_dismantle", "set", "blackwood", 1)
D:modify_unit("militarysite", "empire_castle", "conquers", 14)
D:modify_unit("building", "empire_castle", "vision_range", 14)
D:modify_unit("militarysite", "empire_castle", "heal_per_second", 10)

D:modify_unit("building", "empire_fortress", "buildcost", "remove", "planks")
D:modify_unit("building", "empire_fortress", "buildcost", "remove", "granite")
D:modify_unit("building", "empire_fortress", "buildcost", "remove", "marble")
D:modify_unit("building", "empire_fortress", "buildcost", "remove", "marble_column")
D:modify_unit("building", "empire_fortress", "buildcost", "set", "log", 17)
D:modify_unit("building", "empire_fortress", "return_on_dismantle", "remove", "marble_column")
D:modify_unit("building", "empire_fortress", "return_on_dismantle", "remove", "marble")
D:modify_unit("building", "empire_fortress", "return_on_dismantle", "remove", "granite")
D:modify_unit("building", "empire_fortress", "return_on_dismantle", "remove", "planks")
D:modify_unit("building", "empire_fortress", "return_on_dismantle", "set", "log", 9)
D:modify_unit("militarysite", "empire_fortress", "conquers", 12)
D:modify_unit("building", "empire_fortress", "vision_range", 13)
D:modify_unit("militarysite", "empire_fortress", "max_soldiers", 10)
D:modify_unit("militarysite", "empire_fortress", "heal_per_second", 10)

D:modify_unit("building", "empire_outpost", "buildcost", "remove", "planks")
D:modify_unit("building", "empire_outpost", "buildcost", "remove", "log")
D:modify_unit("building", "empire_outpost", "buildcost", "remove", "marble")
D:modify_unit("building", "empire_outpost", "buildcost", "set", "granite", 11)
D:modify_unit("building", "empire_outpost", "return_on_dismantle", "remove", "marble")
D:modify_unit("building", "empire_outpost", "return_on_dismantle", "set", "granite", 8)
D:modify_unit("militarysite", "empire_outpost", "conquers", 9)
D:modify_unit("building", "empire_outpost", "vision_range", 9)
D:modify_unit("militarysite", "empire_outpost", "max_soldiers", 5)
D:modify_unit("militarysite", "empire_outpost", "heal_per_second", 0)

D:modify_unit("building", "empire_sentry", "buildcost", "remove", "planks")
D:modify_unit("building", "empire_sentry", "buildcost", "remove", "log")
D:modify_unit("building", "empire_sentry", "buildcost", "set", "granite", 5)
D:modify_unit("building", "empire_sentry", "return_on_dismantle", "remove", "planks")
D:modify_unit("building", "empire_sentry", "return_on_dismantle", "set", "granite", 4)
D:modify_unit("militarysite", "empire_sentry", "conquers", 7)
D:modify_unit("building", "empire_sentry", "vision_range", 7)
D:modify_unit("militarysite", "empire_sentry", "max_soldiers", 1)
D:modify_unit("militarysite", "empire_sentry", "heal_per_second", 0)

D:modify_unit("building", "empire_tower", "buildcost", "remove", "planks")
D:modify_unit("building", "empire_tower", "buildcost", "remove", "granite")
D:modify_unit("building", "empire_tower", "buildcost", "remove", "marble_column")
D:modify_unit("building", "empire_tower", "buildcost", "set", "log", 11)
D:modify_unit("building", "empire_tower", "return_on_dismantle", "remove", "planks")
D:modify_unit("building", "empire_tower", "return_on_dismantle", "remove", "granite")
D:modify_unit("building", "empire_tower", "return_on_dismantle", "remove", "marble_column")
D:modify_unit("building", "empire_tower", "return_on_dismantle", "set", "log", 4)
D:modify_unit("militarysite", "empire_tower", "conquers", 5)
D:modify_unit("building", "empire_tower", "vision_range", 17)
D:modify_unit("militarysite", "empire_tower", "max_soldiers", 7)
D:modify_unit("militarysite", "empire_tower", "heal_per_second", 0)

end -- if N
